name: Nightly

on:
  schedule:
    - cron: "0 2 * * *" # run at 2 AM UTC

jobs:
  nightly:
    name: Deploy nightly
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Linux release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/tikz/bcov/releases/79590666/assets%7B?name,label}
          release_id: 79590666
          asset_path: ./bcov.zip
          asset_name: bcov-$$.zip
          asset_content_type: application/zip
          max_releases: 7
