# name: Nightly

# on:
#   push:
#     branches: [main]
#   schedule:
#     - cron: "0 2 * * *" # run at 2 AM UTC


name: Release
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Create Release Folder
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -v ./...

      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
          cache-dependency-path: ./web/package-lock.json
      - run: npm ci --legacy-peer-deps
        working-directory: web
      - run: npm run build --if-present
        working-directory: web

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Deploy Linux release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/tikz/bcov/releases/79590666/assets%7B?name,label}
          release_id: 79590666
          asset_path: ./bcov.zip
          asset_name: bcov-$$.zip
          asset_content_type: application/zip
          max_releases: 7