name: Release

on:
  create:
    tags:
      - v*

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -v ./...

      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
          cache-dependency-path: ./web/package-lock.json
      - run: npm ci --legacy-peer-deps
        working-directory: web
      - run: npm run build --if-present
        working-directory: web

      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "bcov,web/src"
          bodyFile: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}
