name: Release

on:
  create:
    tags:
      - v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
          cache-dependency-path: ./web/package-lock.json

      - name: Build Makefile
        run: make

      - name: Compress
        run: tar -czvf release.tar.gz bcov web/build/

      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          omitBody: true
          artifacts: ${{ github.workspace }}\release.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
